### ISSUE TITLE
No persistent data

### ISSUE THREAD

**Issue by tb0yd** [rentpath/react-redux-starter-kit#1]
The starter kit does not contain a method for persisting data from request to request. Let's come up with a way to do this that makes sense within the context of Redux and Express.

**Comment by tb0yd** [comment]
Here's what I'm thinking:

**Comment by tb0yd** [comment]
Oops - sorry

**Comment by c0** [comment]
Just to revisit —
- Persistent data is handed by an API (see #2)
- For sessions, cookies still work well (over https of course)
