### ISSUE TITLE
Switch to redux-devtools-extension?

### ISSUE THREAD

**Issue by c0** [rentpath/react-redux-starter-kit#11]
[redux-devtools-extension](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/README.md)

Currently, redux dev tools are built and added to the app and are not meant for prod. We can remove the code and switch to the chrome extension, which would also work on prod.

Thoughts?

**Comment by Teapane** [comment]
I would be fine with adding this extension. Seems easy to maintain, since it's updated manually and only requires  **one** line of code :smile:.

**Comment by aribouius** [comment]
:+1:

**Comment by colinrymer** [comment]
:+1:

**Comment by Teapane** [comment]
Working on it. :smile:

**Comment by c0** [comment]
<img src="https://33.media.tumblr.com/f82acd2d94214d2d928b837652723d49/tumblr_niufudazvs1qzr6b2o1_400.gif">

**Comment by Teapane** [comment]
:boom: :stars:
