### ISSUE TITLE
Add comments

### ISSUE THREAD

**Issue by tb0yd** [rentpath/react-redux-starter-kit#3]
Add comments

**Comment by tb0yd** [comment]
@c0 @colinrymer 
Can you review the comments for accuracy? These comments are meant only to give the minimum understanding to know what each file does. I did research mostly by googling and reading Readmes, Github issues, etc.

https://github.com/rentpath/react-redux-starter-kit/compare/107032874_comments?expand=1

**Comment by c0** [comment]
Glad to. Thanks for doing this! Do you mind opening a PR? Then we can comment more effectively.

**Comment by tb0yd** [comment]
Sure - https://github.com/rentpath/react-redux-starter-kit/pull/4
